### ISSUE TITLE
[Feature]: Ability to add the project using Yarn

### ISSUE THREAD

**Issue by jmosley5** [IBMa/equal-access#2141]
### Project

cypress-accessibility-checker

### Description

Currently, we use yarn to manage our packages. As mixing package managers is a bad practice, I tried to install the `cypress-accessibility-checker` using yarn. On setup however, I get the following error. 

```
Error: Webpack Compilation Error
Module build failed: UnhandledSchemeError: Reading from "node:url" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

<img width="1238" alt="SCR-20250103-lcbx" src="https://github.com/user-attachments/assets/b438374e-aa06-46b2-bc0b-76b28ce44c42" />

We are really excited about using this checker as we already use Cypress. But, the error is a blocker for running the tests. If this is an issue instead of a feature request, please let me know what next steps I need to take. Thank you for your time! Excited to see this in the works!

**Comment by panpan-lin** [comment]
We use `npm` but we also started seeing this error after migrating our project from Carbon v10 to Carbon v11. Node version is unchanged (always v20).

**Comment by tombrunet** [comment]
It's hard to say without seeing what else is in your achecker.cy.ts file. 

I ran our small boilerplate with Node 18, 20, and 22. I used Cypress 13.13.1. The pages I'm scanning aren't particularly complicated, but I do not get any errors. I tried with both npm and yarn, but no difference.

The error says that something is trying to import "node:url". The only references I can find in our dependencies to node:url are in the core `@types/node` package, and only in declare blocks. Feels like your error is from something else - or webpack is mis-configured?
